name: Build and Deploy Blueprint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz graphviz-dev

    - name: Install leanblueprint and dependencies
      run: |
        pip install --upgrade pip
        pip install leanblueprint plastex

    - name: Install elan and Lean
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Get Lean version
      run: |
        cd blueprint
        lean --version

    - name: Cache Lake packages
      uses: actions/cache@v3
      with:
        path: .lake
        key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-lake-

    - name: Build Lean project
      run: |
        lake build

    - name: Build blueprint
      run: |
        cd blueprint
        leanblueprint web

    - name: Build API documentation
      run: |
        lake -R -Kenv=dev build RicciFlow:docs
      timeout-minutes: 120

    - name: Prepare deployment directory
      run: |
        mkdir -p _site
        cp -r blueprint/web/* _site/
        mkdir -p _site/docs
        cp -r docs/* _site/docs/
        # Create index redirect
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./index.html">
          <title>Ricci Flow Formalization</title>
        </head>
        <body>
          <p>Redirecting to <a href="./index.html">Blueprint</a>...</p>
        </body>
        </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
