name: Build and Deploy Blueprint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz graphviz-dev

    - name: Install leanblueprint and dependencies
      run: |
        pip install --upgrade pip
        pip install leanblueprint plastex

    - name: Install elan and Lean
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Get Lean version
      run: |
        cd blueprint
        lean --version

    - name: Cache Lake packages
      uses: actions/cache@v3
      with:
        path: .lake
        key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-lake-

    - name: Get Mathlib cache
      run: |
        lake exe cache get

    - name: Build Lean project
      run: |
        lake build

    - name: Check declarations
      run: |
        lake exe checkdecls blueprint/lean_decls

    - name: Build blueprint
      run: |
        cd blueprint
        leanblueprint web

    - name: Prepare deployment directory
      run: |
        mkdir -p _site
        cp -r blueprint/web/* _site/
        # Create a simple redirect for API docs since we don't build doc-gen4
        mkdir -p _site/docs
        cat > _site/docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>API Documentation</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 100px auto; padding: 20px; }
            h1 { color: #333; }
            p { line-height: 1.6; }
            a { color: #0066cc; text-decoration: none; }
            a:hover { text-decoration: underline; }
            .box { background: #f5f5f5; padding: 20px; border-radius: 5px; margin-top: 20px; }
          </style>
        </head>
        <body>
          <h1>API Documentation Not Available</h1>
          <p>The API documentation (generated by doc-gen4) is not currently built to reduce CI/CD time.</p>
          <div class="box">
            <p><strong>To view the source code:</strong></p>
            <ul>
              <li>Browse the <a href="https://github.com/Xinze-Li-Bryan/RicciFlow/tree/main/RicciFlow">RicciFlow source code on GitHub</a></li>
              <li>Read the <a href="../index.html">Blueprint documentation</a> for mathematical details</li>
            </ul>
          </div>
        </body>
        </html>
        EOF

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
